# Generated by Django 4.1.7 on 2024-04-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(blank=True, max_length=200, null=True, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed_at')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due_date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='todouser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
