#build stage
FROM node:21.7 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# 
RUN npm run build 

FROM nginx:stable-alpine as production-stage
# Bash 설치
RUN apk add --no-cache bash

COPY  ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY  ./nginx/wait-for-it.sh /wait-for-it.sh
COPY  ./nginx/docker-entrypoint.production.sh /docker-entrypoint.production.sh
RUN chmod +x /docker-entrypoint.production.sh
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
